In [10]:
#大括號裡面不會顯示重複的資料值
set1:set = {1,1,3,5,3,8,5,10}
set1.add(11)
set1

{1, 3, 5, 8, 10, 11}

In [11]:
for value in set1:
    print(value)

1
3
5
8
10
11


In [12]:
import numpy as np
array1:np.ndarray =np.array(range(1,11))

#陣列運算
array1 + 10 * 50


array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510])

In [13]:
display(np.arange(1.3,3.5,0.1))
display(np.linspace(1,2,20))

array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [14]:
display(np.random.random())
display(np.random.randn(10,5,3))
display(np.random.randint(1,10,size=(10,5)))

0.30639247208142817

array([[[ 0.11643878,  0.41562731, -1.73875427],
        [-1.04945316, -1.31135159, -0.09368694],
        [ 0.12709442, -1.73076755, -0.49391795],
        [-0.7940341 ,  0.59936683,  0.43391371],
        [ 1.51065072, -0.14957756,  0.88149145]],

       [[-0.85772438, -1.19258186, -0.33054445],
        [ 0.87200062, -0.04111486,  0.87122865],
        [ 0.07590372,  0.71735831, -0.15184178],
        [ 1.54352966, -1.16171727,  2.119408  ],
        [-1.26201498,  0.84343215, -0.67430621]],

       [[ 1.34208981,  0.82484201,  0.93867569],
        [-0.22365599,  0.62394558,  0.22871756],
        [-0.5266388 ,  0.13873999, -0.85053126],
        [ 1.06855704,  0.78364305, -0.45179413],
        [-0.78220339, -0.34874742,  0.20507604]],

       [[-0.19777973,  0.58895607,  1.13506915],
        [-0.99215419,  0.68648498, -0.20547553],
        [-0.72754961,  0.48164421,  0.31784017],
        [-1.53302233, -1.22379167, -2.0845394 ],
        [-0.22378412,  0.39204782, -0.29408774]],

       [[ 1.

array([[3, 9, 2, 2, 3],
       [6, 1, 6, 6, 4],
       [1, 3, 5, 1, 4],
       [1, 1, 7, 4, 3],
       [1, 1, 5, 3, 2],
       [2, 3, 8, 8, 4],
       [8, 6, 8, 6, 9],
       [3, 3, 7, 8, 4],
       [2, 9, 6, 8, 4],
       [8, 3, 4, 8, 1]])