In [10]:
#大括號裡面不會顯示重複的資料值
set1:set = {1,1,3,5,3,8,5,10}
set1.add(11)
set1

{1, 3, 5, 8, 10, 11}

In [11]:
for value in set1:
    print(value)

1
3
5
8
10
11


In [12]:
import numpy as np
array1:np.ndarray =np.array(range(1,11))

#陣列運算
array1 + 10 * 50


array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510])

In [13]:
display(np.arange(1.3,3.5,0.1))
display(np.linspace(1,2,20))

array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])